### ISSUE TITLE
album.php getInfo() does not assign tracks to the return variable $info

### ISSUE THREAD

**Issue by mkovalch** [matto1990/PHP-Last.fm-API#10]
Guys, please take a look at http://stackoverflow.com/questions/19618068/using-getinfo-for-album-does-not-return-tracks/21731109#21731109 and my own answer to this issue. Please implement in the future release.

I assigned the variables I needed for my code, but I think there are more (http://www.last.fm/api/show/album.getInfo) :
$i = 0;
			foreach ( $call->album->tracks->track as $track ) {
				$info['tracks'][$i]['name'] = (string) $track->name;
				$info['tracks'][$i]['rank'] =(string)$track['rank'][0];
				$info['tracks'][$i]['duration'] = (string) $track->duration;
				$i++;
			}

**Comment by devilcius** [comment]
Done.
