### ISSUE TITLE
Missing method 'getImages' in artist.php

### ISSUE THREAD

**Issue by samijnih** [matto1990/PHP-Last.fm-API#13]
The method is missing so I wrotten it :

    /**
     * Get all images for an artist on Last.fm.
	 * @param array $methodVars An array with the following values: <i>artist</i> or <i>mbid</i>
	 * @return array
	 */
	public function getImages($methodVars) {
		$vars = array(
			'method'  => 'artist.getinfo',
			'api_key' => $this->auth->apiKey
		);
		$vars = array_merge($vars, $methodVars);
		
		if ( $call = $this->apiGetCall($vars) ) {
			$info['image']['small']      = (string) $call->artist->image[0];
			$info['image']['medium']     = (string) $call->artist->image[1];
			$info['image']['large']      = (string) $call->artist->image[2];
			$info['image']['extralarge'] = (string) $call->artist->image[3];
			$info['image']['mega']       = (string) $call->artist->image[4];

			return $info;
		}
		else {
			return FALSE;
		}
	}

**Comment by matto1990** [comment]
Hi,

Would you mind submitting this as a pull request so I can merge it in.

Thanks

Matt

**Comment by samijnih** [comment]
Yep I will but cannot publish my branch or create a pull request. Do I need some rights ?

**Comment by jensz12** [comment]
@matto1990 This seems to be fixed. So it shold be closed :-)
