### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by samijnih** [matto1990/PHP-Last.fm-API#15]
This is what I see :

    // Pass the array to the auth class to eturn a valid auth
    $auth = new lastfmApiAuth('setsession', $authVars);
    // Call for the album package class with auth data
    $apiClass = new lastfmApi();
    $artistClass = $apiClass->getPackage($auth, 'artist', $config);

- lastfmApi needs a dependency which is an instance of lastfmApiAuth
- lastfmApi::getPackage always needs an instance of lastfmApiAuth

Dependency injection begins here so what I think :

1. Create a constructor for the lastfmApi which takes as first parameter an instance of himself (yes because all classes extends him..). Share the instance in lastfmApi::$auth
2. In lastfmApi::getPackage, remove the first parameters and at the end of this functions when packages are lazy loaded, pass $this->auth to the constructor of each package

Final result :

    // Pass the array to the auth class to eturn a valid auth
    $auth = new lastfmApiAuth('setsession', $authVars);
    // Call for the album package class with auth data
    $apiClass = new lastfmApi($auth);
    $artistClass = $apiClass->getPackage('artist', $config);

Do you agree ? I tested and nothing is broken.

**Comment by matto1990** [comment]
Yes this does look sensible. If you have a pull request for this I can take a look at it.

**Comment by devilcius** [comment]
@samijnih, since version v1.2 `getPackage` is not used anymore. Now API classes are instantiated like this:

```php
$auth = new AuthApi('setsession', array('apiKey' => $apiKey));
$artistApi = new ArtistApi($auth);
´´´
