### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by jensz12** [matto1990/PHP-Last.fm-API#17]
http://www.matto1990.com/projects/phplastfmapi/ just leads to the front page :-)

**Comment by matto1990** [comment]
Unfortunately, I no longer host anything about this project on my website. There was not much information on there anyway. Maybe it can just be removed and the README improved?

**Comment by jensz12** [comment]
@matto1990 That would be fine :-)

**Comment by devilcius** [comment]
@matto1990, that link is not in the README file, but in the project description. Only you can edit it, :smile:

**Comment by matto1990** [comment]
Whoops! Sorry, thought you'd have access to that. Removed it now.
