### ISSUE TITLE
Throw Exceptions instead of calling handleError()

### ISSUE THREAD

**Issue by mikeshiyan** [matto1990/PHP-Last.fm-API#19]
It is a best practice in modern PHP to throw Exceptions of custom type. This way people know something's wrong in the code right away while developing/debugging code.

A big disadvantage of current implementation is that there should be such checks after every single object construction or method call:
```php
    $auth = new AuthApi('setsession', ['apiKey' => $api_key, 'secret' => $api_secret]);

    if (empty($auth->error)) {
      $artist_api = new ArtistApi($auth);

      if (empty($artist_api->error)) {
        $artist_info = $artist_api->getInfo(['artist' => $artist]);
        
        if (empty($artist_api->error)) {
          return $artist_info;
        }
      }
    }
```

**Comment by devilcius** [comment]
You're right, and it was planned long time ago.
